services:
  postgres:
    image: postgres:latest
    container_name: chat_postgres_container
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: root
      POSTGRES_DB: chatdb
    ports:
      - 5432:5432
    volumes:
      - chat_postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: chat_redis_container
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - chat_redis_data:/data

  mongodb:
    image: mongo:latest
    container_name: chat_mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: chatdb
    ports:
      - "27017:27017"
    volumes:
      - chat_mongodb_data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    container_name: chat_zookeeper_container
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka-1:
    image: confluentinc/cp-kafka:5.5.1
    container_name: chat_kafka1_container
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3 # 일반 토픽들의 기본 복제 펙터
      KAFKA_NUM_PARTITIONS: 3 # 파티션 개수 3개

  kafka-2:
    image: confluentinc/cp-kafka:5.5.1
    container_name: chat_kafka2_container
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:29093,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3 # 일반 토픽들의 기본 복제 펙터
      KAFKA_NUM_PARTITIONS: 3 # 파티션 개수 3개

  kafka-3:
    image: confluentinc/cp-kafka:5.5.1
    container_name: chat_kafka3_container
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:29094,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3 # 일반 토픽들의 기본 복제 펙터
      KAFKA_NUM_PARTITIONS: 3 # 파티션 개수 3개

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8989:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:29092, kafka-2:29093, kafka-3:29094
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
volumes:
  chat_postgresql_data:
  chat_redis_data:
  chat_mongodb_data: