server:
  shutdown: graceful
  port: 8082

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:postgresql://localhost:5432/chatdb
    driver-class-name: org.postgresql.Driver
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: localhost
    port: 6379

  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27017/chatdb
      auto-index-creation: true

  kafka:
    broker-port: localhost:9092